
const catsList = [ {
    "length": "12 to 16 inches",
    "origin": "Southeast Asia",
    "image_link": "https://api-ninjas.com/images/cats/abyssinian.jpg",
    "family_friendly": 3,
    "shedding": 3,
    "general_health": 2,
    "playfulness": 5,
    "children_friendly": 5,
    "grooming": 3,
    "intelligence": 5,
    "other_pets_friendly": 5,
    "min_weight": 6,
    "max_weight": 10,
    "min_life_expectancy": 9,
    "max_life_expectancy": 15,
    "name": "Abyssinian"
}, 
{
    "length": "22 to 25 inches, not including tail",
    "origin": "Great Britain",
    "image_link": "https://api-ninjas.com/images/cats/british_shorthair.jpg",
    "family_friendly": 3,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 2,
    "meowing": 4,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 3,
    "other_pets_friendly": 5,
    "min_weight": 7,
    "max_weight": 17,
    "min_life_expectancy": 12,
    "max_life_expectancy": 17,
    "name": "British Shorthair"
  },
  {
    "length": "Medium",
    "origin": "Greece",
    "image_link": "https://api-ninjas.com/images/cats/aegean.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 4,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 7,
    "max_weight": 10,
    "min_life_expectancy": 9,
    "max_life_expectancy": 10,
    "name": "Aegean"
  },
  {
    "length": "Medium",
    "origin": "United States and Canada",
    "image_link": "https://api-ninjas.com/images/cats/american_bobtail.jpg",
    "family_friendly": 4,
    "shedding": 4,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 3,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 13,
    "min_life_expectancy": 11,
    "max_life_expectancy": 15,
    "name": "American Bobtail"
  },
  {
    "length": "Medium",
    "origin": "California, USA",
    "image_link": "https://api-ninjas.com/images/cats/american_curl.jpg",
    "family_friendly": 5,
    "shedding": 4,
    "general_health": 5,
    "playfulness": 4,
    "meowing": 5,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "other_pets_friendly": 4,
    "min_weight": 5,
    "max_weight": 10,
    "min_life_expectancy": 12,
    "max_life_expectancy": 16,
    "name": "American Curl"
  },
  {
    "length": "12 to 15 inches",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/american_shorthair.jpg",
    "family_friendly": 3,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 2,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 7,
    "max_weight": 12,
    "min_life_expectancy": 15,
    "max_life_expectancy": 20,
    "name": "American Shorthair"
  },
  {
    "length": "Medium to large",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/american_wirehair.jpg",
    "family_friendly": 4,
    "shedding": 3,
    "general_health": 5,
    "playfulness": 3,
    "children_friendly": 4,
    "stranger_friendly": 3,
    "grooming": 5,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 8,
    "max_weight": 15,
    "min_life_expectancy": 14,
    "max_life_expectancy": 18,
    "name": "American Wirehair"
  },
  {
    "length": "Medium",
    "origin": "Egypt",
    "image_link": "https://api-ninjas.com/images/cats/egyptian_mau.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 2,
    "children_friendly": 4,
    "stranger_friendly": 2,
    "grooming": 4,
    "other_pets_friendly": 3,
    "min_weight": 6,
    "max_weight": 14,
    "min_life_expectancy": 12,
    "max_life_expectancy": 15,
    "name": "Egyptian Mau"
  },
  {
    "length": "Large",
    "origin": "Cyprus",
    "image_link": "https://api-ninjas.com/images/cats/aphrodite_giant.jpg",
    "family_friendly": 4,
    "shedding": 4,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 2,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 11,
    "max_weight": 24,
    "min_life_expectancy": 12,
    "max_life_expectancy": 15,
    "name": "Aphrodite Giant"
  },
  {
    "length": "Medium",
    "origin": "Saudi Arabia",
    "image_link": "https://api-ninjas.com/images/cats/arabian_mau.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 5,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 8,
    "max_weight": 16,
    "min_life_expectancy": 12,
    "max_life_expectancy": 14,
    "name": "Arabian Mau"
  },
  {
    "length": "Medium",
    "origin": "Great Britain",
    "image_link": "https://api-ninjas.com/images/cats/asian.jpg",
    "family_friendly": 5,
    "shedding": 1,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 4,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 3,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 10,
    "max_weight": 10,
    "min_life_expectancy": 15,
    "max_life_expectancy": 15,
    "name": "Asian"
  },
  {
    "length": "Medium",
    "origin": "Australia",
    "image_link": "https://api-ninjas.com/images/cats/australian_mist.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 2,
    "children_friendly": 4,
    "stranger_friendly": 3,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 8,
    "max_weight": 15,
    "min_life_expectancy": 15,
    "max_life_expectancy": 18,
    "name": "Australian Mist"
  },
  {
    "length": "Up to 18 inches, not including tail",
    "origin": "United States and Thailand",
    "image_link": "https://api-ninjas.com/images/cats/balinese.jpg",
    "family_friendly": 4,
    "shedding": 3,
    "general_health": 2,
    "playfulness": 4,
    "meowing": 1,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "other_pets_friendly": 4,
    "min_weight": 5,
    "max_weight": 10,
    "min_life_expectancy": 9,
    "max_life_expectancy": 15,
    "name": "Balinese"
  },
  {
    "length": "Short",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/bambino.jpg",
    "family_friendly": 4,
    "shedding": 1,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 3,
    "grooming": 2,
    "intelligence": 3,
    "other_pets_friendly": 3,
    "min_weight": 4,
    "max_weight": 9,
    "min_life_expectancy": 9,
    "max_life_expectancy": 15,
    "name": "Bambino"
  },
  {
    "length": "17 to 22 inches, not including tail",
    "origin": "USA",
    "image_link": "https://api-ninjas.com/images/cats/bengal_cats.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 3,
    "playfulness": 5,
    "meowing": 2,
    "children_friendly": 5,
    "stranger_friendly": 3,
    "grooming": 4,
    "intelligence": 5,
    "other_pets_friendly": 5,
    "min_weight": 8,
    "max_weight": 17,
    "min_life_expectancy": 10,
    "max_life_expectancy": 16,
    "name": "Bengal Cats"
  },
  {
    "length": "15 to 18 inches",
    "origin": "Unknown",
    "image_link": "https://api-ninjas.com/images/cats/birman.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 2,
    "playfulness": 4,
    "meowing": 4,
    "children_friendly": 5,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 5,
    "min_weight": 6,
    "max_weight": 12,
    "min_life_expectancy": 12,
    "max_life_expectancy": 16,
    "name": "Birman"
  },
  {
    "length": "13 to 20 inches",
    "origin": "Kentucky, USA",
    "image_link": "https://api-ninjas.com/images/cats/bombay.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 15,
    "min_life_expectancy": 12,
    "max_life_expectancy": 20,
    "name": "Bombay"
  },
  {
    "length": "Medium to large",
    "origin": "Brazil",
    "image_link": "https://api-ninjas.com/images/cats/brazilian_shorthair.jpg",
    "family_friendly": 4,
    "shedding": 1,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 10,
    "max_weight": 22,
    "min_life_expectancy": 14,
    "max_life_expectancy": 20,
    "name": "Brazilian Shorthair"
  },
  {
    "length": "Medium to Large",
    "origin": "Great Britain",
    "image_link": "https://api-ninjas.com/images/cats/british_longhair.jpg",
    "family_friendly": 4,
    "shedding": 4,
    "general_health": 3,
    "playfulness": 3,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 9,
    "max_weight": 18,
    "min_life_expectancy": 15,
    "max_life_expectancy": 17,
    "name": "British Longhair"
  },
  {
    "length": "Medium",
    "origin": "England",
    "image_link": "https://api-ninjas.com/images/cats/burmilla.jpg",
    "family_friendly": 4,
    "shedding": 3,
    "general_health": 3,
    "playfulness": 5,
    "children_friendly": 4,
    "grooming": 4,
    "intelligence": 3,
    "other_pets_friendly": 4,
    "min_weight": 6.5,
    "max_weight": 13,
    "min_life_expectancy": 10,
    "max_life_expectancy": 15,
    "name": "Burmilla"
  },
  {
    "length": "15 to 18 inches",
    "origin": "Burma and Thailand",
    "image_link": "https://api-ninjas.com/images/cats/burmese.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 2,
    "playfulness": 4,
    "children_friendly": 5,
    "stranger_friendly": 5,
    "grooming": 5,
    "intelligence": 5,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 12,
    "min_life_expectancy": 10,
    "max_life_expectancy": 16,
    "name": "Burmese"
  },
  {
    "length": "Medium to Large",
    "origin": "USA",
    "image_link": "https://api-ninjas.com/images/cats/california_spangled.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 2,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 5,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 8,
    "max_weight": 15,
    "min_life_expectancy": 9,
    "max_life_expectancy": 16,
    "name": "California Spangled"
  },
  {
    "length": "Medium",
    "origin": "Burma and Thailand",
    "image_link": "https://api-ninjas.com/images/cats/european_burmese.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 1,
    "playfulness": 5,
    "meowing": 1,
    "children_friendly": 5,
    "stranger_friendly": 5,
    "grooming": 5,
    "intelligence": 5,
    "other_pets_friendly": 5,
    "min_weight": 6,
    "max_weight": 10,
    "min_life_expectancy": 10,
    "max_life_expectancy": 15,
    "name": "European Burmese"
  },
  {
    "length": "12 to 15 inches",
    "origin": "England",
    "image_link": "https://api-ninjas.com/images/cats/havana_brown.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 3,
    "children_friendly": 4,
    "stranger_friendly": 3,
    "grooming": 5,
    "other_pets_friendly": 4,
    "min_weight": 6,
    "max_weight": 10,
    "min_life_expectancy": 10,
    "max_life_expectancy": 15,
    "name": "Havana Brown"
  },
  {
    "length": "Medium",
    "origin": "China and Japan",
    "image_link": "https://api-ninjas.com/images/cats/japanese_bobtail.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 5,
    "meowing": 1,
    "children_friendly": 5,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 5,
    "min_weight": 6,
    "max_weight": 10,
    "min_life_expectancy": 9,
    "max_life_expectancy": 15,
    "name": "Japanese Bobtail"
  },
  {
    "length": "14 to 18 inches, not including tail",
    "origin": "Persia (known as Iran today)",
    "image_link": "https://api-ninjas.com/images/cats/persian.jpg",
    "family_friendly": 3,
    "shedding": 5,
    "general_health": 2,
    "playfulness": 2,
    "meowing": 3,
    "children_friendly": 2,
    "stranger_friendly": 2,
    "grooming": 2,
    "intelligence": 3,
    "other_pets_friendly": 2,
    "min_weight": 7,
    "max_weight": 12,
    "min_life_expectancy": 10,
    "max_life_expectancy": 15,
    "name": "Persian"
  },
  {
    "length": "Small",
    "origin": "USA",
    "image_link": "https://api-ninjas.com/images/cats/napoleon.jpg",
    "family_friendly": 4,
    "shedding": 3,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 2,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 2,
    "intelligence": 3,
    "other_pets_friendly": 4,
    "min_weight": 5,
    "max_weight": 9,
    "min_life_expectancy": 9,
    "max_life_expectancy": 15,
    "name": "Napoleon"
  },
  {
    "length": "Small to medium",
    "origin": "Oregon, USA",
    "image_link": "https://api-ninjas.com/images/cats/laperm.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 5,
    "meowing": 5,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "other_pets_friendly": 4,
    "min_weight": 5,
    "max_weight": 8,
    "min_life_expectancy": 10,
    "max_life_expectancy": 15,
    "name": "LaPerm"
  },
  {
    "length": "Medium to large",
    "origin": "Kuril Islands",
    "image_link": "https://api-ninjas.com/images/cats/kurilian_bobtail.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 5,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 15,
    "min_life_expectancy": 15,
    "max_life_expectancy": 20,
    "name": "Kurilian Bobtail"
  },
  {
    "length": "Medium",
    "origin": "Southeast Asia",
    "image_link": "https://api-ninjas.com/images/cats/mekong_bobtail.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 5,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 10,
    "min_life_expectancy": 15,
    "max_life_expectancy": 18,
    "name": "Mekong Bobtail"
  },
  {
    "length": "Medium to long",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/nebelung.jpg",
    "family_friendly": 4,
    "shedding": 4,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 2,
    "children_friendly": 2,
    "stranger_friendly": 2,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 7,
    "max_weight": 15,
    "min_life_expectancy": 11,
    "max_life_expectancy": 18,
    "name": "Nebelung"
  },
  {
    "length": "Medium",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/oriental_bicolor.jpg",
    "family_friendly": 4,
    "shedding": 1,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 5,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 8,
    "max_weight": 12,
    "min_life_expectancy": 8,
    "max_life_expectancy": 12,
    "name": "Oriental Bicolor"
  },
  {
    "length": "Medium",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/chantilly-tiffany.jpg",
    "family_friendly": 4,
    "shedding": 3,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 5,
    "children_friendly": 4,
    "stranger_friendly": 2,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 3,
    "min_weight": 6,
    "max_weight": 12,
    "min_life_expectancy": 7,
    "max_life_expectancy": 16,
    "name": "Chantilly-Tiffany"
  },
  {
    "length": "15 to 18 inches",
    "origin": "France",
    "image_link": "https://api-ninjas.com/images/cats/chartreux.jpg",
    "family_friendly": 3,
    "shedding": 4,
    "general_health": 4,
    "playfulness": 3,
    "meowing": 5,
    "children_friendly": 3,
    "stranger_friendly": 3,
    "grooming": 2,
    "other_pets_friendly": 4,
    "min_weight": 7,
    "max_weight": 16,
    "min_life_expectancy": 11,
    "max_life_expectancy": 15,
    "name": "Chartreux"
  },
  {
    "length": "Large",
    "origin": "Egypt",
    "image_link": "https://api-ninjas.com/images/cats/chausie.jpg",
    "family_friendly": 4,
    "shedding": 1,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 1,
    "stranger_friendly": 3,
    "grooming": 5,
    "intelligence": 5,
    "other_pets_friendly": 4,
    "min_weight": 15,
    "max_weight": 30,
    "min_life_expectancy": 12,
    "max_life_expectancy": 14,
    "name": "Chausie"
  },
  {
    "length": "Medium to large",
    "origin": "China",
    "image_link": "https://api-ninjas.com/images/cats/chinese_li_hua.jpg",
    "family_friendly": 3,
    "shedding": 3,
    "general_health": 3,
    "playfulness": 4,
    "children_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 9,
    "max_weight": 12,
    "min_life_expectancy": 9,
    "max_life_expectancy": 16,
    "name": "Chinese Li Hua"
  },
  {
    "length": "Small to medium",
    "origin": "England",
    "image_link": "https://api-ninjas.com/images/cats/colorpoint_shorthair.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 2,
    "playfulness": 5,
    "meowing": 1,
    "children_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 5,
    "max_weight": 10,
    "min_life_expectancy": 12,
    "max_life_expectancy": 17,
    "name": "Colorpoint Shorthair"
  },
  {
    "length": "Small",
    "origin": "United Kingdom",
    "image_link": "https://api-ninjas.com/images/cats/cornish_rex.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 3,
    "playfulness": 5,
    "meowing": 2,
    "children_friendly": 5,
    "stranger_friendly": 5,
    "grooming": 5,
    "intelligence": 4,
    "other_pets_friendly": 5,
    "min_weight": 6,
    "max_weight": 10,
    "min_life_expectancy": 11,
    "max_life_expectancy": 15,
    "name": "Cornish Rex"
  },
  {
    "length": "Medium to large",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/highlander.jpg",
    "family_friendly": 4,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 3,
    "intelligence": 4,
    "other_pets_friendly": 5,
    "min_weight": 10,
    "max_weight": 20,
    "min_life_expectancy": 10,
    "max_life_expectancy": 15,
    "name": "Highlander"
  },
  {
    "length": "17 to 19 inches",
    "origin": "United States",
    "image_link": "https://api-ninjas.com/images/cats/himalayan.jpg",
    "family_friendly": 4,
    "shedding": 5,
    "general_health": 2,
    "playfulness": 1,
    "children_friendly": 2,
    "stranger_friendly": 2,
    "grooming": 1,
    "other_pets_friendly": 2,
    "min_weight": 7,
    "max_weight": 12,
    "min_life_expectancy": 9,
    "max_life_expectancy": 15,
    "name": "Himalayan"
  },
  {
    "length": "10 to 12 inches",
    "origin": "Thailand",
    "image_link": "https://api-ninjas.com/images/cats/khao_manee.jpg",
    "family_friendly": 4,
    "shedding": 1,
    "general_health": 3,
    "playfulness": 5,
    "meowing": 4,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 10,
    "min_life_expectancy": 10,
    "max_life_expectancy": 12,
    "name": "Khao Manee"
  },
  {
    "length": "13 to 20 inches, not including tail",
    "origin": "USA",
    "image_link": "https://api-ninjas.com/images/cats/savannah.jpg",
    "family_friendly": 4,
    "shedding": 3,
    "general_health": 5,
    "playfulness": 5,
    "meowing": 3,
    "children_friendly": 4,
    "stranger_friendly": 5,
    "grooming": 4,
    "intelligence": 5,
    "other_pets_friendly": 5,
    "min_weight": 8,
    "max_weight": 20,
    "min_life_expectancy": 17,
    "max_life_expectancy": 20,
    "name": "Savannah"
  },
  {
    "length": "10 to 12 inches",
    "origin": "Tayside, Scotland",
    "image_link": "https://api-ninjas.com/images/cats/scottish_fold.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 3,
    "playfulness": 3,
    "meowing": 4,
    "children_friendly": 5,
    "stranger_friendly": 3,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 6,
    "max_weight": 13,
    "min_life_expectancy": 11,
    "max_life_expectancy": 14,
    "name": "Scottish Fold"
  },
  {
    "length": "Medium to long",
    "origin": "Philadelphia, USA",
    "image_link": "https://api-ninjas.com/images/cats/snowshoe.jpg",
    "family_friendly": 5,
    "shedding": 3,
    "general_health": 5,
    "playfulness": 5,
    "meowing": 2,
    "children_friendly": 5,
    "stranger_friendly": 4,
    "grooming": 5,
    "intelligence": 5,
    "other_pets_friendly": 4,
    "min_weight": 7,
    "max_weight": 12,
    "min_life_expectancy": 14,
    "max_life_expectancy": 19,
    "name": "Snowshoe"
  },
  {
    "length": "Medium",
    "origin": "Russia",
    "image_link": "https://api-ninjas.com/images/cats/peterbald.jpg",
    "family_friendly": 5,
    "shedding": 1,
    "general_health": 3,
    "playfulness": 4,
    "meowing": 4,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 2,
    "intelligence": 3,
    "other_pets_friendly": 4,
    "min_weight": 6,
    "max_weight": 10,
    "min_life_expectancy": 12,
    "max_life_expectancy": 15,
    "name": "Peterbald"
  },
  {
    "length": "20 to 24 inches",
    "origin": "Washington, USA",
    "image_link": "https://api-ninjas.com/images/cats/pixie-bob.jpg",
    "family_friendly": 5,
    "shedding": 4,
    "general_health": 5,
    "playfulness": 4,
    "meowing": 3,
    "children_friendly": 5,
    "stranger_friendly": 3,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 4,
    "min_weight": 8,
    "max_weight": 17,
    "min_life_expectancy": 13,
    "max_life_expectancy": 15,
    "name": "Pixie-Bob"
  },
  {
    "length": "Small",
    "origin": "Singapore",
    "image_link": "https://api-ninjas.com/images/cats/singapura.jpg",
    "family_friendly": 5,
    "shedding": 2,
    "general_health": 4,
    "playfulness": 4,
    "meowing": 5,
    "children_friendly": 4,
    "stranger_friendly": 4,
    "grooming": 4,
    "intelligence": 5,
    "other_pets_friendly": 4,
    "min_weight": 4,
    "max_weight": 7,
    "min_life_expectancy": 11,
    "max_life_expectancy": 15,
    "name": "Singapura"
  },
  {
    "length": "13 to 15 inches",
    "origin": "Canada",
    "image_link": "https://api-ninjas.com/images/cats/sphynx.jpg",
    "family_friendly": 5,
    "shedding": 1,
    "general_health": 2,
    "playfulness": 4,
    "children_friendly": 5,
    "stranger_friendly": 5,
    "grooming": 2,
    "intelligence": 4,
    "other_pets_friendly": 5,
    "min_weight": 6,
    "max_weight": 12,
    "min_life_expectancy": 8,
    "max_life_expectancy": 14,
    "name": "Sphynx"
  }
]

module.exports = {catsList}